
#include "power_module.h"
const power_rail_cfg_t power_analog_3300 = {
    .nominal_mv = 3300,
    .ov_threshold_mv = 3400,
    .uv_threshold_mv = 3000,
    .on_delay_ms = 5,
    .off_delay_ms = 5,
    .timeout_ms = 10,
    .dependency_mask = 0,
    .rail_group_mask = 0,
    .monitor_type = PWR_MON_ANALOG,
    .margin_capable = false,
    .margin_high_pct = 0,
    .margin_low_pct = 0,
    .enable_active_high = true,
    .en_port = 0,
    .en_pin_bit = 11
};
const power_rail_cfg_t power_analog_5000 = {
    .nominal_mv = 5000,
    .ov_threshold_mv = 5100,
    .uv_threshold_mv = 4000,
    .on_delay_ms = 10,
    .off_delay_ms = 20,
    .timeout_ms = 100,
    .dependency_mask = 0,
	.enabled = true,
    .rail_group_mask = 0,
    .monitor_type = PWR_MON_ANALOG,
    .margin_capable = false,
    .margin_high_pct = 0,
    .margin_low_pct = 0,
    .enable_active_high = true,
    .en_port = 0,
    .en_pin_bit = 12
};
const power_rail_cfg_t power_analog_1200 = {
    .nominal_mv = 12000,
    .ov_threshold_mv = 12010,
    .uv_threshold_mv = 11890,
    .on_delay_ms = 2,
    .off_delay_ms = 30,
    .timeout_ms = 10,
    .dependency_mask = 0,
	.enabled = true,
    .rail_group_mask = 0,
    .monitor_type = PWR_MON_ANALOG,
    .margin_capable = false,
    .margin_high_pct = 0,
    .margin_low_pct = 0,
    .enable_active_high = true,
    .en_port = 0,
    .en_pin_bit = 15
};
const power_rail_cfg_t power_digital_2400 = {
    .nominal_mv = 2400,
    .ov_threshold_mv = 2405,
    .uv_threshold_mv = 2395,
    .on_delay_ms = 60,
    .off_delay_ms = 0,
    .timeout_ms = 0,
    .dependency_mask = 0,
	.enabled = true,
    .rail_group_mask = 0,
    .monitor_type = PWR_MON_DIGITAL,
    .margin_capable = false,
    .margin_high_pct = 0,
    .margin_low_pct = 0,
    .enable_active_high = true,
    .en_port = 0,
    .en_pin_bit = 3
};
const power_rail_cfg_t power_digital_OFFLINE = {
    .nominal_mv = 2400,
    .ov_threshold_mv = 2405,
    .uv_threshold_mv = 2395,
    .on_delay_ms = 60,
    .off_delay_ms = 0,
    .timeout_ms = 0,
    .dependency_mask = 0,
	.enabled = false,
    .rail_group_mask = 0,
    .monitor_type = PWR_MON_DIGITAL,
    .margin_capable = false,
    .margin_high_pct = 0,
    .margin_low_pct = 0,
    .enable_active_high = true,
    .en_port = 0,
    .en_pin_bit = 3
};
const power_controller_cfg_t power_controller_basic = {
    .watchdog_enabled = false,
    .watchdog_timeout_ms = 0,
    .active_rail_group = 0,
    .gpi_mask = 0,
    .gpo_mask = 0,
    .pmbus_address = 0,
    .cascade_id = 0,
    .cascade_count = 1,
    .sync_clock_enabled = false,
    .fault_pin_asserted = false
};