/*  LLVM

  This is from Ian and shows how to implement printf redirect when using LLVM compiler.
  
  
*/

#include "hal_data.h"
#include <stdio.h>
#include <sys/stat.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

int uart_putc(char c, FILE *file);

// Your custom UART output function. You must implement this.
volatile bool g_uart5_tx_complete_flag = false;

FILE __stdio = FDEV_SETUP_STREAM(uart_putc,
                    NULL,
                    NULL,
                    _FDEV_SETUP_WRITE);

FILE *const stdout = &__stdio;

/* Callback function */
void g_uart5_callback(uart_callback_args_t *p_args)
{
    if (UART_EVENT_TX_DATA_EMPTY == p_args->event)
    {
        g_uart5_tx_complete_flag = true;
    }
}

int uart_putc(char c, FILE *file)
{
    fsp_err_t err;
    int ret;

    FSP_PARAMETER_NOT_USED(file);

    ret = (int)c;

    g_uart5_tx_complete_flag = false;

    err = R_SCI_UART_Write(&g_uart5_ctrl, (uint8_t *)&c, (uint32_t)1);
    if (FSP_SUCCESS != err)
    {
        __BKPT(2);

        ret = -1;
    }

    if (FSP_SUCCESS == err)
    {
        while(false == g_uart5_tx_complete_flag);
    }

    return ret;;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    fsp_err_t err;

    err = R_SCI_UART_Open(&g_uart5_ctrl, &g_uart5_cfg);
    if (FSP_SUCCESS != err)
    {
        __BKPT(1);
    }

    while(1)
    {
        printf("Hello\n");
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
